#!/usr/bin/env python3
"""Test vectors for a Switchboard client: login signature, ticket, envelope keys and a sealed box.

    testkit/.venv/bin/python testkit/vectors.py            # check docs/test-vectors.json
    testkit/.venv/bin/python testkit/vectors.py --write    # regenerate it

Every input is fixed (private keys, nonces, ids), so the outputs are too: Ed25519 signatures are
deterministic, and the box uses the fixed nonce below instead of a random one. Your client should
reproduce every output from the inputs. Never use a fixed nonce outside a test.
"""
import argparse, hashlib, json, os, sys

from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305

import sb

PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "docs", "test-vectors.json")


def vectors():
    phone = sb.Keys(sign=sb.b64e(bytes([1]) * 32), box=sb.b64e(bytes([2]) * 32))
    mac = sb.Keys(sign=sb.b64e(bytes([3]) * 32), box=sb.b64e(bytes([4]) * 32))
    host, challenge = "switchboard.example", bytes([7]) * 32
    msg_id, nonce = bytes([5]) * 16, bytes([6]) * 12
    code = "0123456789abcdef0123456789abcdef"
    plaintext = sb.inner({"t": "req", "method": "GET", "path": "/hello", "headers": {}}, b"hi")

    login = sb.LOGIN_PREFIX + host.encode() + b"\n" + challenge
    k_phone_to_mac = sb._key(phone.box, mac.key, phone.id, mac.id)
    k_mac_to_phone = sb._key(mac.box, phone.key, mac.id, phone.id)
    aad = sb.b64d(mac.id) + sb.b64d(phone.id) + msg_id
    box = nonce + ChaCha20Poly1305(k_phone_to_mac).encrypt(nonce, plaintext, aad)
    assert sb.open_box(mac, phone.id, phone.key, sb.b64e(msg_id), box) == plaintext

    b = sb.b64e
    return {
        "about": "Switchboard v1 test vectors. Bytes are base64url without padding, as on the wire. "
                 "Generated by testkit/vectors.py; see docs/protocol.md.",
        "inputs": {
            "phone_sign_private": phone.private()["sign"], "phone_box_private": phone.private()["box"],
            "mac_sign_private": mac.private()["sign"], "mac_box_private": mac.private()["box"],
            "host": host, "challenge_nonce": b(challenge), "pairing_code": code,
            "message_id": b(msg_id), "box_nonce": b(nonce), "plaintext": b(plaintext),
        },
        "outputs": {
            "phone_id": phone.id, "phone_key": phone.key, "mac_id": mac.id, "mac_key": mac.key,
            "login_message": b(login), "login_sig": b(phone.sign.sign(login)),
            "ticket": hashlib.sha256(code.encode()).hexdigest(),
            "envelope_key_phone_to_mac": b(k_phone_to_mac), "envelope_key_mac_to_phone": b(k_mac_to_phone),
            "aad_phone_to_mac": b(aad), "box_phone_to_mac": b(box),
        },
    }


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    v = vectors()
    if ap.parse_args().write:
        with open(PATH, "w") as f:
            json.dump(v, f, indent=2)
            f.write("\n")
        print("wrote", PATH)
    elif json.load(open(PATH)) != v:
        sys.exit("docs/test-vectors.json doesn't match: the client code in testkit/sb.py changed")
    else:
        print("ok: docs/test-vectors.json matches testkit/sb.py")
